config/routes.rb
RGErp::Application.routes.draw do 

  resources :leave_types
  resources :leaves 
  root :to => redirect("/users/sign_in")
  devise_for :users, :skip => "registrations"
  match "/save_password"  => "users#save_password", :via => [:put]
  match "/change_password"  => "users#change_password"
  match "/search"  => "users#search", :via => [:get,:post]
  match "/calendar"  => "leaves#calendar", :via => [:get,:post]
  match "/get_leave_count_per_user" => "leaves#get_leave_count_per_user", :via => [:get,:post]
  match "/get_leave_status" => "users#get_leave_status", :via => [:get,:post]
  match "/send_leave_notification" => "leaves#send_leave_notification", :via => [:get,:post]
  

  resources :users
  namespace :admin do
    resources :users  do
      get 'block_user'
      get 'unblock_user'
    end
  end

  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable,:lockable#, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :admin, :color
  attr_accessible :leave_type_users
  
   belongs_to :user_group
   ##########################
   has_many :leaves, :class_name=>"Leave",:dependent => :destroy
   has_many :leave_types, :through => :leaves
   has_many :leave_type_users, :dependent => :destroy

   ##########################
   validates :name, :presence => { :message => "can't be blank!" }, :on => :create
   validates :email, :presence => { :message => "can't be blank!" }
   validates :email,:format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/,:message => "format is invalid!" },:allow_blank => true
   validates :color, :uniqueness => true  ##Unique leaves and total sum of all leaves per user
  def self.get_uniq_leaves_per_user(usr_id,lv_id)    
    #leaves = Leave.find_by_sql("SELECT user_id,leave_type_id, sum(days) as days from leaves where user_id = #{usr_id} group by leave_type_id, user_id") 
    leaves = Leave.find_by_sql("SELECT user_id,leave_type_id, sum(days) as days from leaves where user_id = #{usr_id} and leave_type_id = #{lv_id} group by leave_type_id, user_id")      
  end
  
  def generate_confirmation_token
     self.confirmation_token = self.class.confirmation_token
     self.confirmation_sent_at = Time.now.utc
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_admin
  before_filter :get_user, :only =>[:block_user, :unblock_user]
  
  def index
    @users = User.where("admin =?", false).order("name ASC")
  end 
 
  def new
    @user = User.new
  end
  
  def create
    @lvtype = []
    @user = User.new(params[:user])
    @user.password = Devise.friendly_token[0,20]
    respond_to do |format|
      if @user.save
       @lvtype = params[:leave_type_users]
       @lvtype.each_with_index do |lv,i|
         LeaveTypeUser.create(:user_id=>@user.id,:leave_type_id=>lv[0],:leave_count=>lv[1]["leave_count"])
        end
        format.html { redirect_to admin_users_path, :notice => "User '#{@user.name}' was successfully created." }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  def block_user
    @user.lock_access! if @user
    redirect_to admin_users_path
  end
  
  def unblock_user
    @user.unlock_access! if @user
    redirect_to admin_users_path
  end
  
  def destroy
    @user = User.find(params[:id])
    ##Adding back all the quantities after user deletion
    # @user.inventory_users.each do |u_i|
	  # @s = Inventory.find u_i.inventory_id	
	  # @qt_val = @s.qty.to_i + u_i.qty.to_i
	  # @s.update_column(:qty,@qt_val)
     # end	  
     @user.destroy
     respond_to do |format|
        format.html { redirect_to admin_users_path, :notice => "User '#{@user.name}' was successfully deleted." }
        format.json { head :no_content }
     end
  end
  
  def show
    #user=User.find params[:id]
    #@inventory_users=user.inventory_users
    @user=User.find params[:id]
    # @leaves = User.get_uniq_leaves_per_user(@user.id)
  end
  
   def edit
    @user=User.find params[:id]
   end

   def update
     @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_path, notice: "User '#{@user.name}' was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
   end
  
  private
    def authenticate_admin
      if !current_user.admin?
        sign_out current_user 
        flash[:notice] = "Please logged in as admin to continue."
        redirect_to new_user_session_path
      end
    end  
    
    def get_user
      @user = User.find_by_id params[:user_id]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :assign_user
  def assign_user
     @user = current_user
  end

  def save_password
    if @user.update_attributes(params[:user])
       sign_in(@user, :bypass => true)
        flash[:notice] = "Password changed successfully."
	redirect_to  '/change_password'
    else
      respond_to do |format|
        format.html { render :action => "change_password" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def get_leave_status
    @user = User.where("id=?",params[:user_id]).first 
    @user_id = @user.id  
    p '~~~~~~~~~~~~~~'
    p @user_id
    p '-------------------' 
    render :partial => "user_leave_status"
  end
  
  def search   
    str = "%#{params[:q]}%"; 
	comp_data = ""
    persons = User.find(:all, :conditions => ["name LIKE ? AND admin = ? AND locked_at is null",str, 0])
     comp_data1 = ""
    persons.each do|comp_res1|
      comp_data += "#{comp_res1.name}|#{comp_res1.id}\n";
    end
    if comp_data != ""
       render :text=> comp_data 
     else
      render :text=> "<a>Create a new user</a>|n_per|"
    end  
  end
  
  
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_leave_status.html.erb
<style>
  table th,table td  {padding-left: 10px;}
</style>
<div>
<table class="user_leave_status">
  <thead>
    <tr>
      <th>Leave type</th>
      <!-- <th>Allocated type</th> -->
      <th>Leaves Taken</th>
      <th>Leaves Balance</th>
    </tr>
  </thead>  
  <tbody>
    <% LeaveType.find(:all, :order => 'id').each do |account|%>
      <tr>
       <td><%=account.type_name %></td>
       <% actual =  LeaveTypeUser.by_user_and_leave_type(@user.id,account.id) %>
       <!-- <td><%#= actual.first.leave_count if actual.first %>
       </td> -->
       <% taken =  User.get_uniq_leaves_per_user(@user.id,account.id) %>
       <td><%= !taken.blank? ? taken.first.days : "0" %></td>
       <td><%= actual.first.present? ? actual.first.leave_count - (!taken.blank? ? taken.first.days : 0) : 0 %></td>
      </tr>  
    <%end%>
  </tbody>
</table>
<br/>
<%if @user.leaves.present?%>
  <h5>Last leave taken :</h5>
  <table class="user_leave_status">
    <thead>
    <tr>   
      <th>From date</th>
      <th>To date</th>
      <th>Days</th>
      <th>Reason</th>
      <th>Leave Type</th>
    </tr>
  </thead>
  <tbody>
    <% last_three = Leave.where(:user_id => @user.id).last(3) %>
    <% last_three.each do |u| %>
      <tr>  
        <td><%= u.from_date.strftime("%d %b %y") %></td>
        <td><%= u.to_date.strftime("%d %b %y") %></td>
        <td><%= u.days %></td>
        <td style="text-align: left"><%= u.reason %></td>
        <td><%= u.leave_type.type_name %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
<%end%>
</div>
<% unless last_three.nil? %>
  <div class="fr" style="margin-top: 10px">
    <% if @user %>
    <%= link_to "Show History","/admin/users/#{@user.id}"%>
  <% end %>
  </div>
<% end %>

app/views/users/change_password.html.erb
<div align="center">
<%= form_for @user, :url => save_password_path, :html => { :method => :put, :class => "form-horizontal well", :style => "width:350px;text-align:left" } do |f| %>
<% if @user.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div><%= f.label :password %><%= f.password_field :password, :autocomplete => "off" %></div>

  <div><%= f.label :password_confirmation %><%= f.password_field :password_confirmation %></div><br />

  <div><%= f.submit "Update" , :class=>"btn btn-primary"%>
  <%#= link_to t('.back', :default => t("helpers.links.back")),
              home_path, :class => 'btn'  %></div>
<% end %>
</div>

app/views/users/show.html.erb
<%#- model_class = InventoryUser -%>
<div class="page-header">
  <h1><%#=t '.title', :default => model_class.model_name.human %></h1>
</div>
<% #if products.count > 0%>
  <div class="label label-success">Inventory Information</div>
    <%#@inventory_users.each do |inv_user|%>  
      <dl class="dl-horizontal">
        <dt><strong><%#= model_class.human_attribute_name(:item_name) %>:</strong></dt>
        <dd><%#= inv_user.inventory.item_name %></dd>
        <dt><strong><%#= model_class.human_attribute_name(:qty) %>:</strong></dt>
        <dd><%#= inv_user.qty %></dd>
        <dt><strong><%#= model_class.human_attribute_name(:date) %>:</strong></dt>
        <dd><%#= inv_user.created_at.strftime("%d, %m-%Y") %></dd>
      </dl>
      <div style="border-bottom:1px solid lightgrey;height:2px;width:500px;"></div>
    <% #end %>
<% #end %>  