config/routes.rb
RGErp::Application.routes.draw do 

  resources :leave_types
  resources :leaves 
  root :to => redirect("/users/sign_in")
  devise_for :users, :skip => "registrations"
  match "/save_password"  => "users#save_password", :via => [:put]
  match "/change_password"  => "users#change_password"
  match "/search"  => "users#search", :via => [:get,:post]
  match "/calendar"  => "leaves#calendar", :via => [:get,:post]
  match "/get_leave_count_per_user" => "leaves#get_leave_count_per_user", :via => [:get,:post]
  match "/get_leave_status" => "users#get_leave_status", :via => [:get,:post]
  match "/send_leave_notification" => "leaves#send_leave_notification", :via => [:get,:post]
  

  resources :users
  namespace :admin do
    resources :users  do
      get 'block_user'
      get 'unblock_user'
    end
  end

  
  

end

app/controllers/leave_types_controller.rb
class LeaveTypesController < ApplicationController
  # GET /leave_types
  # GET /leave_types.json
  def index
    @leave_types = LeaveType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leave_types }
    end
  end

  # GET /leave_types/1
  # GET /leave_types/1.json
  def show
    @leave_type = LeaveType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leave_type }
    end
  end

  # GET /leave_types/new
  # GET /leave_types/new.json
  def new
    @leave_type = LeaveType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leave_type }
    end
  end

  # GET /leave_types/1/edit
  def edit
    @leave_type = LeaveType.find(params[:id])
  end

  # POST /leave_types
  # POST /leave_types.json
  def create
    @leave_type = LeaveType.new(params[:leave_type])

    respond_to do |format|
      if @leave_type.save
        format.html { redirect_to leave_types_path, notice: 'Leave type was successfully created.' }
        format.json { render json: @leave_type, status: :created, location: @leave_type }
      else
        format.html { render action: "new" }
        format.json { render json: @leave_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leave_types/1
  # PUT /leave_types/1.json
  def update
    @leave_type = LeaveType.find(params[:id])

    respond_to do |format|
      if @leave_type.update_attributes(params[:leave_type])
        format.html { redirect_to leave_types_path, notice: 'Leave type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leave_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leave_types/1
  # DELETE /leave_types/1.json
  def destroy
    @leave_type = LeaveType.find(params[:id])
    @leave_type.destroy



    respond_to do |format|
      format.html { redirect_to leave_types_url, notice: "Leave type successfully deleted." }
      format.json { head :no_content }
    end
  end
end

app/helpers/leave_types_helper.rb
module LeaveTypesHelper
end

app/views/leave_types/_form.html.erb
<%= javascript_include_tag 'jquery',"bootstrap-colorpicker" %>
<script>
$(function(){
$('#leave_type_color').attr('value','#e81456');
	//$('.colorpicker').colorpicker({
	//	format: 'hex'
	//});
	// Events demo
       $('#cp3').colorpicker({format: 'hex',color:'#e81456'})
          // .on('change.color', function(evt, color){
          //      // alert("test1")
          //     $('#leave_type_color').attr('style','color:'+color);
          // })
          //.on('mouseover.color', function(evt, color){
          // alert("test2")
          //    // $('#title').attr('style','background-color:'+color);
         //})
	
});
     
</script>

<%= form_for @leave_type ,:html => { :class => 'form-horizontal well' } do |f| %>
  <% if @leave_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leave_type.errors.count, "error") %> prohibited this leave_type from being saved:</h2>

      <ul>
      <% @leave_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>	
  
   <div class="control-group">
    <label class='control-label'>Leave Type</label>
    <div class="controls">
     <%= f.text_field :type_name, :class => 'text_field',:required => "true" %>
    </div>
  </div>
  
   <div class="control-group">
    <label class='control-label'>Color</label>
    <div class="controls">
     <div class="input-append color" data-color="#e81456" data-color-format="hex" id="cp3">
			<%= f.text_field :color, :class => 'colorpicker text_field',:required => "true", :readonly =>"true" , :style=>"width:100px"%>
			<span class="add-on" style="margin-top: 1px;"><i style="background-color: #e81456;"></i></span>			
			</div>		


    </div>
  </div>
  

   <div class="control-group">
    <label class='control-label'>Count</label>
    <div class="controls">
         <%= f.text_field :leave_count, :class => 'text_field',:required => "true"%>


    </div>
    </div>
    
   <div class="control-group">
    <label class='control-label'>Description</label>
    <div class="controls">
         <%= f.text_area :description, :class => 'text_field',:required => "true", :rows=>3 %>
    </div>
    </div>
  
   <div class="control-group">
    <label class='control-label'>Optional</label>
    <div class="controls">  
      <%= f.radio_button :is_optional, true %> Yes
      <%= f.radio_button :is_optional, false%> No
    </div>
    </div>
 
  
  <div class="form-actions">
     <%= f.submit "Submit", :class => 'btn btn-primary' %>
       <%= link_to t('.cancel',
                      :default => t("helpers.links.cancel")),
                      leave_types_path, :class => 'btn' %>

  </div>
  
<% end %>

app/views/leave_types/edit.html.erb
<%= render 'form' %>

<%#= link_to 'Show', @leave_type %> 
<%#= link_to 'Back', leave_types_path %>

app/views/leave_types/index.html.erb
<table class="table table-striped" id="leave_type_tbl">
  <thead>
   <tr>
    <th>Type</th>
    <th>Color</th>
    <th>Leave count</th>
    <th>Action</th>   
   </tr>
  </thead>
<tbody>
<% @leave_types.each do |leave_type| %>
  <%#=leave_type.class%>


  <tr>
    <td><%= leave_type.type_name %></td>
    <td><div style="width:20px;height:20px;-webkit-border-radius: 10px;-moz-border-radius: 10px;border-radius: 10px;border:1px solid #E8FFF1;background-color:<%= leave_type.color %>;-webkit-box-shadow: #B3B3B3 3px 3px 3px;-moz-box-shadow: #B3B3B3 3px 3px 3px; box-shadow: #B3B3B3 3px 3px 3px;"></div></td>
    <td><%= leave_type.leave_count %></td>
    <td><%#= link_to 'Show', leave_type , :class => 'btn btn-mini' %>
    <%= link_to 'Edit', edit_leave_type_path(leave_type)  , :class => 'btn btn-mini' %>
    <%= link_to 'Destroy', leave_type, method: :delete, data: { confirm: 'Are you sure?' }  , :class => 'btn btn-mini btn-danger'%></td>
  </tr>
  
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Leave type', new_leave_type_path ,  :class => 'btn btn-primary' %>

app/views/leave_types/new.html.erb
<!-- Set the width of new leave_type page  -->
<div class="container" style="width: 70%">


<!-- <div class="border-form-div span9"> -->
	<div class="">  
		<%= render :partial => 'form' %>  
	</div>
</div>


<%#= link_to 'Back', leave_types_path %>

app/views/leave_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @leave_type.option %>
</p>

<p>
  <b>Color:</b>
  <%= @leave_type.color %>
</p>

<p>
  <b>Leave count:</b>
  <%= @leave_type.leave_count %>
</p>


<%= link_to 'Edit', edit_leave_type_path(@leave_type) %> |
<%= link_to 'Back', leave_types_path %>