config/routes.rb
RGErp::Application.routes.draw do 

  resources :leave_types
  resources :leaves 
  root :to => redirect("/users/sign_in")
  devise_for :users, :skip => "registrations"
  match "/save_password"  => "users#save_password", :via => [:put]
  match "/change_password"  => "users#change_password"
  match "/search"  => "users#search", :via => [:get,:post]
  match "/calendar"  => "leaves#calendar", :via => [:get,:post]
  match "/get_leave_count_per_user" => "leaves#get_leave_count_per_user", :via => [:get,:post]
  match "/get_leave_status" => "users#get_leave_status", :via => [:get,:post]
  match "/send_leave_notification" => "leaves#send_leave_notification", :via => [:get,:post]
  

  resources :users
  namespace :admin do
    resources :users  do
      get 'block_user'
      get 'unblock_user'
    end
  end

  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable,:lockable#, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :admin, :color
  attr_accessible :leave_type_users
  
   belongs_to :user_group
   ##########################
   has_many :leaves, :class_name=>"Leave",:dependent => :destroy
   has_many :leave_types, :through => :leaves
   has_many :leave_type_users, :dependent => :destroy

   ##########################
   validates :name, :presence => { :message => "can't be blank!" }, :on => :create
   validates :email, :presence => { :message => "can't be blank!" }
   validates :email,:format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/,:message => "format is invalid!" },:allow_blank => true
   validates :color, :uniqueness => true  ##Unique leaves and total sum of all leaves per user
  def self.get_uniq_leaves_per_user(usr_id,lv_id)    
    #leaves = Leave.find_by_sql("SELECT user_id,leave_type_id, sum(days) as days from leaves where user_id = #{usr_id} group by leave_type_id, user_id") 
    leaves = Leave.find_by_sql("SELECT user_id,leave_type_id, sum(days) as days from leaves where user_id = #{usr_id} and leave_type_id = #{lv_id} group by leave_type_id, user_id")      
  end
  
  def generate_confirmation_token
     self.confirmation_token = self.class.confirmation_token
     self.confirmation_sent_at = Time.now.utc
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_admin
  before_filter :get_user, :only =>[:block_user, :unblock_user]
  
  def index
    @users = User.where("admin =?", false).order("name ASC")
  end 
 
  def new
    @user = User.new
  end
  
  def create
    @lvtype = []
    @user = User.new(params[:user])
    @user.password = Devise.friendly_token[0,20]
    respond_to do |format|
      if @user.save
       @lvtype = params[:leave_type_users]
       @lvtype.each_with_index do |lv,i|
         LeaveTypeUser.create(:user_id=>@user.id,:leave_type_id=>lv[0],:leave_count=>lv[1]["leave_count"])
        end
        format.html { redirect_to admin_users_path, :notice => "User '#{@user.name}' was successfully created." }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  def block_user
    @user.lock_access! if @user
    redirect_to admin_users_path
  end
  
  def unblock_user
    @user.unlock_access! if @user
    redirect_to admin_users_path
  end
  
  def destroy
    @user = User.find(params[:id])
    ##Adding back all the quantities after user deletion
    # @user.inventory_users.each do |u_i|
	  # @s = Inventory.find u_i.inventory_id	
	  # @qt_val = @s.qty.to_i + u_i.qty.to_i
	  # @s.update_column(:qty,@qt_val)
     # end	  
     @user.destroy
     respond_to do |format|
        format.html { redirect_to admin_users_path, :notice => "User '#{@user.name}' was successfully deleted." }
        format.json { head :no_content }
     end
  end
  
  def show
    #user=User.find params[:id]
    #@inventory_users=user.inventory_users
    @user=User.find params[:id]
    # @leaves = User.get_uniq_leaves_per_user(@user.id)
  end
  
   def edit
    @user=User.find params[:id]
   end

   def update
     @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_path, notice: "User '#{@user.name}' was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
   end
  
  private
    def authenticate_admin
      if !current_user.admin?
        sign_out current_user 
        flash[:notice] = "Please logged in as admin to continue."
        redirect_to new_user_session_path
      end
    end  
    
    def get_user
      @user = User.find_by_id params[:user_id]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :assign_user
  def assign_user
     @user = current_user
  end

  def save_password
    if @user.update_attributes(params[:user])
       sign_in(@user, :bypass => true)
        flash[:notice] = "Password changed successfully."
	redirect_to  '/change_password'
    else
      respond_to do |format|
        format.html { render :action => "change_password" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def get_leave_status
    @user = User.where("id=?",params[:user_id]).first 
    @user_id = @user.id  
    p '~~~~~~~~~~~~~~'
    p @user_id
    p '-------------------' 
    render :partial => "user_leave_status"
  end
  
  def search   
    str = "%#{params[:q]}%"; 
	comp_data = ""
    persons = User.find(:all, :conditions => ["name LIKE ? AND admin = ? AND locked_at is null",str, 0])
     comp_data1 = ""
    persons.each do|comp_res1|
      comp_data += "#{comp_res1.name}|#{comp_res1.id}\n";
    end
    if comp_data != ""
       render :text=> comp_data 
     else
      render :text=> "<a>Create a new user</a>|n_per|"
    end  
  end
  
  
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for :user, :url => {:action => "create"},:html => { :class => 'form-horizontal well' } do |f| %>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul style="color:red;">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
   <div class="control-group">
    <label class='control-label'>Name</label>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field',:required => "true" ,:onkeyup=>"this.value=this.value.replace (/(^\s*)/gi, '').replace (/[ ]{2,}/gi,' ')"%>
    </div>
  </div>  

   <div class="control-group">
    <label class='control-label'>Email</label>
    <div class="controls">
      <%= f.email_field :email, :class => 'text_field',:required => "true",:onkeyup=>"this.value=this.value.replace (/(^\s*)/gi, '').replace (/[ ]{2,}/gi,' ')" %>
    </div>
  </div>

  <div class="control-group">
      <label class='control-label'>Color</label>
      <div class="controls">
       <div class="input-append color" data-color="#e81456" data-color-format="hex" id="usercp3">
        <%= f.text_field :color, :class => 'colorpicker text_field',:required => "true", :readonly =>"true" , :style=>"width:100px"%>
        <span class="add-on" style="margin-top: 1px;"><i style="background-color: #e81456;"></i></span>     
        </div>
      </div>
    </div>
  
  <% i=1  %>
    <% LeaveType.find(:all, :order => 'id').each do |account|%>
     <div class="control-group">
       <% unless account.is_optional? %>
         <label class='control-label'><%=account.type_name %> </label>
           <div class="controls"> 
           <%#=lvt.select :leave_type_id, LeaveType.find(:all, :order => 'id').collect {|c| [ , c.id ]}, {:include_blank => '- Select Leave Type -'},  :required => "true"%> 
            <%#= hidden_field_tag "leave_type_id", :value=>account.id %>   


		<%= text_field_tag "leave_type_users[#{account.id}][leave_count]", "",:class => 'text_field',:required => "true" ,:onkeyup=>"this.value=this.value.replace (/(^\s*)/gi, '').replace (/[ ]{2,}/gi,' ')", :style=>"width:50px", :onkeypress=>"return numbersonly(event);", :onblur => 'chk_assign_leave(this," ' +  account.leave_count.to_s  + ' ")', :required => true %>
		
		&nbsp;&nbsp;&nbsp;   
		<span style="font-style:italic">(max: <%=account.leave_count%>)</span>
		<%#= select_year(0, :prompt => 'Year',:start_year => Time.now.year, :end_year => Time.now.year+14,:name=>"year", 'data-encrypted-name' =>"year" ,:html_options=>{:class=>"drop_down",:style=>"width:50px;"})%>
		<%#= select_tag "credit", "",((0..7)) %>

	   </div>
         <% else %>
            <label class='control-label'>&nbsp;</label>
            <%= check_box_tag "leave_type_users[#{account.id}][leave_count]", account.leave_count%>
            <%=account.option %> 
         <% end %>    
       
     </div>
     <%i+=1%>   
    <%end%>     

  
  <div class="form-actions">
     <%= f.submit "Submit", :class => 'btn btn-primary' %>
     <%= link_to t('.cancel',
              :default => t("helpers.links.cancel")),
              admin_users_path, :class => 'btn' %>

  </div>
 
 
 
<% end %>
<%= javascript_include_tag 'jquery',"bootstrap-colorpicker" %>
<script>
  $(function(){
  $('#user_color').attr('value','#e81456');
    $('#usercp3').colorpicker({format: 'hex',color:'#e81456'})
    
  });     
</script>

app/views/admin/users/_show_history_button.html.erb
<% if @user %>
	<%= link_to "Show History","/admin/users/#{@user.id}", :class => 'btn btn-primary' %>
<% end %>

app/views/admin/users/change_password.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put, :class => "form-horizontal well" }) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :required => true %></div>

  <div><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
  <%= f.password_field :password, :autocomplete => "off" %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
  <%= f.password_field :current_password %></div>

  <div><%= f.submit "Update" , :class=>"btn btn-primary"%></div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete %>.</p>

<%= link_to "Back", :back %>

app/views/admin/users/edit.html.erb
<%= form_for :user, :url => {:controller=>"admin/users",:action => "update", :id=>params[:id]},:method=>"PUT",:html => { :class => 'form-horizontal well' } do |f| %>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul style="color:red;">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <table class="table table-striped" id="newtab">
	<thead>
	    <tr>
	      <th>Name</th>
	      <th>Email</th>
        <th>Color</th>
	    </tr>
	  </thead>
	  <tbody>
	     <tr>	 
            <td>
		          <%= f.text_field :name, :class => 'text_field',:required => "true" ,:onkeyup=>"this.value=this.value.replace (/(^\s*)/gi, '').replace (/[ ]{2,}/gi,' ')"%>
		        </td>
  
            <td>
	             <%= f.text_field :email, :class => 'text_field',:required => "true",:onkeyup=>"this.value=this.value.replace (/(^\s*)/gi, '').replace (/[ ]{2,}/gi,' ')" %>
	         </td>
           <td>
             <div class="input-append color" data-color="<%=@user.color%>" data-color-format="hex" id="usercp3">
              <%= f.text_field :color, :class => 'colorpicker text_field',:required => "true", :readonly =>"true"%>
              <span class="add-on" style="margin-top: 1px;"><i style="background-color: <%=@user.color%>;"></i></span>     
              </div>    
            </td>
            <td>		
		          <%= f.submit "Submit", :class => 'btn btn-primary' %>
              <%= link_to t('.cancel', 
                                      :default => t("helpers.links.cancel")),
                                      admin_users_path, :class => 'btn' %>
	          </td>
  
          </tr>
	      </tbody>
      </table>
<% end %>
<%= javascript_include_tag 'jquery',"bootstrap-colorpicker" %>
<script>
  $(function(){
  $('#user_color').attr('value','<%=@user.color%>');
    $('#usercp3').colorpicker({format: 'hex',color:'<%=@user.color%>'})
    
  });     
</script>

app/views/admin/users/index.html.erb
<%- model_class = User -%>

<table class="table table-striped" id="users_list">
  <thead>
    <tr>    
      <th style="width:270px"><%= model_class.human_attribute_name(:name) %></th>
      <th style="width:270px"><%= model_class.human_attribute_name(:color) %></th>
      <th style="width:300px"><%= model_class.human_attribute_name(:email) %></th>
      <th style="width:200px"><%= model_class.human_attribute_name(:created_at) %></th>
      <th style="width:150px"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>        
        <!--  Check if user is assigned any inventory item -->
            
          <%= link_to user.name, admin_user_path(user.id) %>

        </td>
        <td><div style="width:20px;height:20px;-webkit-border-radius: 10px;-moz-border-radius: 10px;border-radius: 10px;border:1px solid #E8FFF1;background-color:<%= user.color %>;-webkit-box-shadow: #B3B3B3 3px 3px 3px;-moz-box-shadow: #B3B3B3 3px 3px 3px; box-shadow: #B3B3B3 3px 3px 3px;"></div></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.strftime("%m/%d/%Y") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_user_path(user), :class => 'btn btn-mini' %>
         
          <% if user.access_locked? %>
            <%= link_to t('.unblock'),
                       admin_user_unblock_user_path(user),
                       :class => 'btn btn-mini' %>
            
          <% else %>
            <%= link_to t('.block'),
                       admin_user_block_user_path(user),
                       :class => 'btn btn-mini' %>
            
          <% end %>
           <%= link_to "Delete",                     
                      admin_user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => "Are you sure you want to delete user '#{user.name}'?")) },
                      :class => 'btn btn-mini btn-danger' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<%= link_to "Add New",
            new_admin_user_path,
            :class => 'btn btn-primary' %>

<script>
jQuery(function() {
  return $('#users_list').dataTable({
    "order": [[ 0, "asc" ]],
    sPaginationType: "full_numbers",
    bJQueryUI: true,
    bProcessing: true,
    "aoColumnDefs": [
          { 'bSortable': false, 'aTargets': [ 1, 4 ] }
       ]

  });
});

</script>

app/views/admin/users/new.html.erb
<%- model_class = User -%>
<!-- Set the width of new user page  -->
<div class="container " style="width:70%">
	<div class="">  
		<%= render :partial => 'form' %>
	</div>
</div>

app/views/admin/users/show.html.erb
<h3>Leave history of '<%=@user.name%>'</h3>

<div class="form_con pad_2" style="width:80%">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Leave type</th>
      <th>Allocated type</th> 
      <th>Leave taken</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
    <% LeaveType.find(:all, :order => 'id').each do |account|%>
      <tr>
       <td><%=account.type_name %></td>
       <% actual =  LeaveTypeUser.by_user_and_leave_type(@user.id,account.id) %>
       <td><%= actual.first.leave_count if actual.first %>
       <%#= alc.first.leave_count %>
       </td>
       <% taken =  User.get_uniq_leaves_per_user(@user.id,account.id) %>
       <td><%= !taken.blank? ? taken.first.days : "0" %></td>
       <td><%= actual.first.leave_count - (!taken.blank? ? taken.first.days : 0) if actual.first %></td>
      </tr>  
    <%end%>
  </tbody>
</table>
</div>
<br/>    
 <table class="table table-striped" id="leave_tbl">
  <thead>
  <tr>   
    <th>From date</th>
    <th>To date</th>
    <th>Days</th>
    <th>Reason</th>
    <th>Leave Type</th>
  </tr>
</thead>
<tbody>
<% @user.leaves.each do |leave| %>
  <tr>  
    <td><%= leave.from_date.strftime("%d %b %y") %></td>
    <td><%= leave.to_date.strftime("%d %b %y") %></td>
    <td><%= leave.days %></td>
    <td><%= leave.reason %></td>
    <td><%= leave.leave_type.type_name %></td>
  </tr>
<% end %>
</tbody>
</table>  
<br/>
        
                      
<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_users_path, :class => 'btn btn-primary'  %>