config/routes.rb
RGErp::Application.routes.draw do 

  resources :leave_types
  resources :leaves 
  root :to => redirect("/users/sign_in")
  devise_for :users, :skip => "registrations"
  match "/save_password"  => "users#save_password", :via => [:put]
  match "/change_password"  => "users#change_password"
  match "/search"  => "users#search", :via => [:get,:post]
  match "/calendar"  => "leaves#calendar", :via => [:get,:post]
  match "/get_leave_count_per_user" => "leaves#get_leave_count_per_user", :via => [:get,:post]
  match "/get_leave_status" => "users#get_leave_status", :via => [:get,:post]
  match "/send_leave_notification" => "leaves#send_leave_notification", :via => [:get,:post]
  

  resources :users
  namespace :admin do
    resources :users  do
      get 'block_user'
      get 'unblock_user'
    end
  end

  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LTS - Leave Tracking System" %></title>
	  <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>    

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", "static", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%=link_to "Leave Tracking system", '/calendar', :class => "brand"%>

          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
               <%if user_signed_in? and current_user.admin?%>
           <%if (params[:controller] == "leaves") && (params[:action] != "calendar") %><li class="active_mnu"><%else%><li><%end%>
            <%= link_to "Leave", leaves_path  %></li>
           <%if params[:controller] == "leave_types"%><li class="active_mnu"><%else%><li><%end%>
            <%= link_to "Leave Type", leave_types_path  %></li>
           <%if params[:controller] == "admin/users"%><li class="active_mnu"><%else%><li><%end%>
            <%= link_to "User", admin_users_path  %></li>
          
               <%end%>
                <% if user_signed_in?%>
                <li>
                  <div class="btn-group">
                    <a class="btn btn-inverse" href="javascript:void(0)"><%= current_user.name.capitalize %></a> 
                    <a class="btn btn-inverse dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Change Password", change_password_path %></li>
                      <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete   %></li>
                    </ul>
                  </div>
                </li>
               
              <% else %>
              
              <% if !(params[:controller] == "devise/sessions" && params[:action] == "new" )%>
                <li><%= link_to "Sign In", new_user_session_path %></li>
              <% end %>
               <!-- <li><%#= link_to "Sign Up", new_user_registration_path %></li> -->
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
    
    <div class="container-fluid">
      <div class="row-fluid">
    
      <% if user_signed_in? && params[:action] != "work_order_sheet" %>
    <div class="page-header">
      <h1><%#=t '.title', :default => model_class.model_name.human.pluralize %>
        <% if (params[:controller] == "leaves" && params[:action] == "index") %>
        Listing leaves
        <%elsif (params[:controller] == "leaves" && params[:action] == "new") %>
        New leave
        <%elsif (params[:controller] == "leaves" && params[:action] == "edit") %>
        Editing leave       
        <%elsif (params[:controller] == "leave_types" && params[:action] == "index") %>
        Listing Leave Type
        <%elsif (params[:controller] == "leave_types" && params[:action] == "new") %>
        New Leave Type
        <%elsif (params[:controller] == "leave_types" && params[:action] == "edit") %>
        Editing Leave Type
        <%elsif (params[:controller] == "inventories" && params[:action] == "show") %>
        Inventory
        <%elsif (params[:controller] == "inventories" && params[:action] == "new") %>
        New Inventory
       
        <%end%>
      </h1>
   </div>
          <!--<div class="span7 fl">
            <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <%if current_user.admin?%>
            <li><%= link_to "Calendar View", "/calendar"  %></li>
            <li><%= link_to "Leave Management", leaves_path  %></li>
            
            <li><%= link_to "Leave Type Management", leave_types_path  %></li>
          <% if params[:controller] == "admin/users" %>
            <li class="active_mnu"><%= link_to "User Management", admin_users_path  %></li>
          <%else%>  
            <li><%= link_to "User Management", admin_users_path  %></li>
          <%end%>
          
               <%end%>
                
              </ul>
            </div>
          </div> -->
      <%end%>
      <% if user_signed_in? && current_user.admin?%>
       <!-- <div  class="span27 fl">-->
        <div>
      <% else %>
        <div>
      <% end %>
      <%# if !((bootstrap_flash.include?("Signed in successfully.")) || (("You need to sign in or sign up before continuing."))) %>
      <% if !(bootstrap_flash.include?("Signed in successfully.")) %>
                   <%= bootstrap_flash %>
     <%end%>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->
  <div class="push_down"></div>
  <footer>
        <div class="footer_bg">Developed by <a href="http://www.andolasoft.com/" target="_blank">Andolasoft</a> (<b><i>Team ROR</b></i>)</div>
    </footer>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    

  </body>
</html>